base = "ocean"
syntax = "base16-ocean.dark"

[ui]
toc_bg = "reset"
toc_border = "#585b70"
content_bg = "reset"
scrollbar_hover = "#b4befe"
status_bg = "reset"
status_separator = "#6c7086"
status_brand_fg = "#1e1e2e"
status_brand_bg = "#89b4fa"
status_filename_fg = "#cdd6f4"
status_filename_bg = "#313244"
status_watch_fg = "#1e1e2e"
status_watch_bg = "#a6e3a1"
status_reloaded_fg = "#1e1e2e"
status_reloaded_bg = "#89b4fa"
status_search_fg = "#f9e2af"
status_search_bg = "#313244"
status_success_fg = "#a6e3a1"
status_success_bg = "#313244"
status_warning_fg = "#f9e2af"
status_error_fg = "#f38ba8"
status_error_bg = "#313244"
status_shortcut_fg = "#7f849c"
status_percent_fg = "#89b4fa"
toc_hover_fg = "#cdd6f4"
toc_header_fg = "#7f849c"
toc_active_bg = "#313244"
toc_inactive_bg = "reset"
toc_accent = "#89b4fa"
toc_index_inactive = "#6c7086"
toc_primary_active = "#cdd6f4"
toc_primary_inactive = "#bac2de"
toc_secondary_inactive = "#6c7086"
toc_secondary_text_active = "#b4befe"
toc_secondary_text_inactive = "#7f849c"

[markdown]
search_highlight_bg = "#45475a"
search_match_bg = "#f9e2af"
code_gutter = "#6c7086"
blockquote_marker = "#7f849c"
list_level_1 = "#cba6f7"
list_level_2 = "#94e2d5"
list_level_3 = "#74c7ec"
ordered_list = "#89b4fa"
table_border = "#45475a"
table_separator = "#585b70"
table_header = "#cba6f7"
table_cell = "#cdd6f4"
heading_1 = "#cdd6f4"
heading_2 = "#94e2d5"
heading_3 = "#cba6f7"
heading_4 = "#74c7ec"
heading_other = "#b4befe"
heading_underline = "#45475a"
code_frame = "#45475a"
code_label = "#7f849c"
inline_code_fg = "#fab387"
inline_code_bg = "#313244"
rule = "#45475a"
link_icon = "#89b4fa"
link_text = "#89b4fa"
link_hover = "#b4befe"
blockquote_text = "#bac2de"
text = "#cdd6f4"
strong_text = "#fab387"
latex_inline_fg = "#cba6f7"
latex_inline_bg = "#313244"
latex_block_fg = "#cba6f7"
mermaid_keyword = "#cba6f7"
mermaid_arrow = "#89dceb"
mermaid_label = "#94e2d5"
mermaid_block_fg = "#cdd6f4"
mark_fg = "#1e1e2e"
mark_bg = "#f9e2af"
task_checked = "#94e2d5"
task_unchecked = "#7f849c"
alert_note = "#89b4fa"
alert_tip = "#a6e3a1"
alert_important = "#cba6f7"
alert_warning = "#f9e2af"
alert_caution = "#f38ba8"
