[ mgr ]
show_hidden = true
linemode = "size"

[opener]
edit = [
  { run = "${EDITOR:-vi} %s", desc = "$EDITOR",      for = "unix",    block = true },
  { run = "sudo ${EDITOR:-vi} %s", desc = "sudo $EDITOR", for = "unix",    block = true },
  { run = "code %s",          desc = "code",         for = "windows", orphan = true },
  { run = "code -w %s",       desc = "code (block)", for = "windows", block = true },
]

[[plugin.prepend_previewers]]
url = "*.{md,markdown,mdown,mkd,mkdn,mdx}"
run = "leaf"

[[plugin.prepend_fetchers]]
id    = "git" # Remove if Yazi > v26.1.22
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
id    = "git" # Remove if Yazi > v26.1.22
url   = "*/"
run   = "git"
group = "git"
